### ISSUE TITLE
PhantomJS doesn't get stopped

### ISSUE THREAD

**Issue by TrafeX** [site5/phantoman#20]
Hi,

I'm running into the issue that PhantomJS doesn't get stopped after all tests are done, however Phantoman says PhantomJS is stopped.

When I dump the `proc_get_status` output in the `stopServer()` methode just before the check to see if the process is still running I get this:

```php
array(8) {
  'command' =>
  string(68) "'/vagrant/vendor/phantomjs/phantomjs/bin/phantomjs' --webdriver=4444"
  'pid' =>
  int(11708)
  'running' =>
  bool(false)
  'signaled' =>
  bool(true)
  'stopped' =>
  bool(false)
  'exitcode' =>
  int(-1)
  'termsig' =>
  int(15)
  'stopsig' =>
  int(0)
}
```

But, when I check the processlist, I see PhantomJS having a different pid.
 
`11709 pts/0    Sl+    0:14 /vagrant/vendor/phantomjs/phantomjs/bin/phantomjs --webdriver=4444`

When I check the processlist during the tests, I get the following:
```bash
vagrant  11704  0.0  0.0   4444   648 pts/0    S+   09:52   0:00  |                   \_ sh -c php /vagrant/vendor/bin/codecept run acceptance --xml
vagrant  11705 38.4  1.0 313364 20536 pts/0    S+   09:52   0:01  |                       \_ php /vagrant/vendor/bin/codecept run acceptance --xml
vagrant  11708  0.0  0.0   4444   644 pts/0    S+   09:52   0:00  |                           \_ sh -c '/vagrant/vendor/phantomjs/phantomjs/bin/phantomjs' --webdriver=4444
vagrant  11709 38.0  0.2  77840  5116 pts/0    t+   09:52   0:00  |                               \_ /vagrant/vendor/phantomjs/phantomjs/bin/phantomjs --webdriver=4444
```

So it seems the parent process is already gone when Phantoman tries to stop PhantomJS, but the child/fork keeps running forever.

This is a snippet of the strace output:
```
11705 09:54:59.242989 kill(11708, SIGTERM) = 0
11708 09:54:59.243379 <... wait4 resumed> 0x7ffff0f3138c, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
11708 09:54:59.243525 --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=11705, si_uid=1000} ---
11708 09:54:59.243770 +++ killed by SIGTERM +++
11705 09:54:59.243817 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=11708, si_status=SIGTERM, si_utime=0, si_stime=0} ---
11705 09:54:59.244031 write(5, "Stopping PhantomJS Server", 25) = 25
11702 09:54:59.244249 <... read resumed> "Stopping PhantomJS Server", 8192) = 25
11705 09:54:59.244340 wait4(11708,  <unfinished ...>
11702 09:54:59.244419 write(1, "Stopping PhantomJS Server", 25 <unfinished ...>
11705 09:54:59.244494 <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGTERM}], WNOHANG|WSTOPPED, NULL) = 11708
11702 09:54:59.244929 <... write resumed> ) = 25
11702 09:54:59.245107 read(3,  <unfinished ...>
11705 09:54:59.245303 write(1, "array(8) {\n  'command' =>\n  string(68) \"'/vagrant/vendor/phantomjs/phantomjs/bin/phantomjs' --webdriver=4444\"\n  'pid' =>\n  int(11708)\n  'running' =>\n  bool(false)\n  'signaled' =>\n  bool(true)\n  's
topped' =>\n  bool(false)\n  'exitcode' =>\n  int(-1)\n  'termsig' =>\n  int(15)\n  'stopsig' =>\n  int(0)\n}\n", 298) = 298
11702 09:54:59.245508 <... read resumed> "array(8) {\n  'command' =>\n  string(68) \"'/vagrant/vendor/phantomjs/phantomjs/bin/phantomjs' --webdriver=4444\"\n  'pid' =>\n  int(11708)\n  'running' =>\n  bool(false)\n  'signaled' =>\n  bool(t
rue)\n  'stopped' =>\n  bool(false)\n  'exitcode' =>\n  int(-1)\n  'termsig' =>\n  int(15)\n  'stopsig' =>\n  int(0)\n}\n", 8192) = 298
11705 09:54:59.245588 wait4(11708,  <unfinished ...>
11702 09:54:59.245640 write(1, "array(8) {\n  'command' =>\n  string(68) \"'/vagrant/vendor/phantomjs/phantomjs/bin/phantomjs' --webdriver=4444\"\n  'pid' =>\n  int(11708)\n  'running' =>\n  bool(false)\n  'signaled' =>\n  bool(true)\n  's
topped' =>\n  bool(false)\n  'exitcode' =>\n  int(-1)\n  'termsig' =>\n  int(15)\n  'stopsig' =>\n  int(0)\n}\n", 298 <unfinished ...>
11705 09:54:59.245720 <... wait4 resumed> 0x7fff16378714, WNOHANG|WSTOPPED, NULL) = -1 ECHILD (No child processes)
11705 09:54:59.248683 write(5, "\n", 1 <unfinished ...>
11702 09:54:59.248759 <... write resumed> ) = 298
11705 09:54:59.248816 <... write resumed> ) = 1
11702 09:54:59.248873 read(3, "\n", 8192) = 1
11705 09:54:59.249160 write(5, "PhantomJS server stopped\n", 25 <unfinished ...>
11702 09:54:59.249238 write(1, "\n", 1 <unfinished ...>
11705 09:54:59.249321 <... write resumed> ) = 25
11705 09:54:59.249633 close(8 <unfinished ...>
11702 09:54:59.249747 <... write resumed> ) = 1
11705 09:54:59.249805 <... close resumed> ) = 0
11702 09:54:59.249931 read(3,  <unfinished ...>
11705 09:54:59.250118 wait4(11708,  <unfinished ...>
11702 09:54:59.250188 <... read resumed> "PhantomJS server stopped\n", 8192) = 25
11705 09:54:59.250255 <... wait4 resumed> 0x7fff163787cc, WNOHANG, NULL) = -1 ECHILD (No child processes)
11702 09:54:59.250344 write(1, "PhantomJS server stopped\n", 25 <unfinished ...>
11705 09:54:59.250413 close(13)         = 0
11702 09:54:59.250743 <... write resumed> ) = 25
11705 09:54:59.250874 close(11 <unfinished ...>
11702 09:54:59.250932 read(3,  <unfinished ...>
11705 09:54:59.251034 <... close resumed> ) = 0
```

What I find strange is that the strace shows the parent process gets killed by something, after tracing it further I found out it get's killed by `proc_terminate()` which is registered as shutdown function and gets executed before `stopServer()`.

I'm diving deeper into this, when I find something I let you know.

**Comment by grantlucas** [comment]
Thanks for the report @TrafeX. I can take a look into this soon and see what I can find.

**Comment by igorsantos07** [comment]
I **think** I accidentaly figured out your issue while working on a similar task at my day job.
It seems when we use `proc_open()` PHP spawns a process that created a child process with the actual target. `proc_get_status()` will return you information on the first process, not the child one. And killing the first one will not do the trick: you need to kill the child.
I'll be working on this today and if it work, I'll share with you what I get :)

**Comment by grantlucas** [comment]
It looks like [PHPBuiltinServer](https://github.com/tiger-seo/PhpBuiltinServer) was/is experiencing the same problem. *This is the repo I originally based Phantoman off of.*

@igorsantos07 Looks like [their solution](https://github.com/tiger-seo/PhpBuiltinServer/pull/4/files) is the same as yours with `exec` at the beginning of the command.

**Comment by grantlucas** [comment]
Looks like I can't add `exec` in the command as that will fail on Windows.

**Comment by grantlucas** [comment]
@TrafeX @igorsantos07 Can you give PR #26  a try and let me know if it works for you?

Set up composer to the following to test

```yaml
"site5/phantoman": "dev-fix/PhantomJSNotStopping",
```

**Comment by igorsantos07** [comment]
Not sure if I'm late here @grantlucas, but I was unable to install the branch version. Maybe Composer doesn't understand slashes in branch names?

```
~/dev/myproject/codeception  composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                        
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package site5/phantoman could not be found in any version, there may be a typo in the package name.

[...]

~/dev/myproject/codeception  grep phantoman composer.json
28:    "site5/phantoman": "dev-fix/PhantomJSNotStopping",
```

**Comment by TrafeX** [comment]
@igorsantos07 I had the same issue, but fixed it by adding the repo to composer:
```php
  "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:site5/phantoman.git"
        }
    ]
```

**Comment by igorsantos07** [comment]
The issue wasn't solved, @grantlucas :(
The child process remains active. Although, in `ps aux` it status changes from `Sl+` to `Sl` after the test is finished, if this helps you in any way.

**Comment by TrafeX** [comment]
@grantlucas I've managed to fix this by adding `exec` to the PhantomJS command.
This is a known issue, see: https://github.com/symfony/symfony/issues/5759 https://bugs.php.net/bug.php?id=39992

**Comment by grantlucas** [comment]
Thanks for the link to the symfony discussion and giving `exec` a try. I'll look at getting `exec` usage implemented for unix environments.

**Comment by grantlucas** [comment]
# TODO

- [ ] Use `exec` approach *only* for Unix environments
- [ ] Test for whether `exec` is available with `which` just to be sure it's available before using it
- [ ] Leave the Windows implementation as it was

**Comment by igorsantos07** [comment]
@grantlucas, it seems `exec` is part of the Unix Shell. `which exec` actually returns nothing because it's part of the kernel itself :)

**Comment by tralafiti** [comment]
Implemented a quick fix with exec on non Windows systems as discussed here to mitigate the problem till you looked into other packages as described in your todo. See #36 

Would be thankful if you could merge this an release it as 1.0.8.

**Comment by grantlucas** [comment]
PR #36 has now been merged so that non-windows systems have `exec` prefixed in the command. Thanks @tralafiti!

Phantoman has now been tagged with `v1.0.8` to address this change.

@igorsantos07 & @TrafeX Please let me know if this works out for you!!

**Comment by grantlucas** [comment]
Closing this issue for now as I think #36 has addressed the issue. Please re-open if not the case.
